filter:
    excluded_paths:
        - 'vendor/*'
        - '*/vendor/*'
        - 'languages/*'
        - 'asstes/js/jquery-qrcode.min.js'

tools:
    external_code_coverage: false
    php_code_sniffer: true
    js_hint: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, languages]